spring.application.name=DmartApplication
spring.datasource.url=jdbc:postgresql://localhost:5432/Dmart_Database
spring.datasource.username=shivakumar
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver