spring.application.name=DmartApplication
spring.datasource.url=jdbc:postgresql://localhost:5432/Dmart_Database
spring.datasource.username=postgres
spring.datasource.password=Sidhu@123
spring.datasource.driver-class-name=org.postgresql.Driver